spring:
  jpa:
    database: POSTGRESQL
#    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/lumus-ms-db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver


